mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls', namespace='news'))
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns=[
    path('', views.posthome, name='post_list'),
    path('postdetail/<slug:post>/<int:pk>/', views.postdetail, name='post_detail'),
    path('postcategory/', views.PostCategory.as_view(), name='post_category'),
    path('relation/', views.relation, name='post_ralation'),
    path('videodetail/<slug:post>/<int:pk>/', views.videodetail, name='video_detail'),
    path('sliddetaill/<int:pk>/', views.sliddetail, name='slid_detail'),
    path('contactus/', views.contactus, name='contact_us'),
    path('videocategory/', views.videocategory, name='video_category'),

]

news/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


# Create your models here.

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    CATEGORY_CHOICES = (
        ('eghtesadi', 'اقتصادی'),
        ('siasi', 'سیاسی'),
        ('varzeshi', 'ورزشی'),
        ('ostani', 'استانی'),
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    body = models.TextField()
    photo = models.ImageField(upload_to='images/Article/')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    category = models.CharField(max_length=15, choices=CATEGORY_CHOICES)

    class Meta:
        ordering = ('-publish',)

    def get_absolute_url(self, ):
        return reverse('news:post_detail', args=[self.slug, self.id])

    def __str__(self, ):
        return self.title


class Slid(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    title = models.CharField(max_length=250)
    body = models.TextField()
    photo = models.ImageField(upload_to='images/Article/')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')


    def get_absolute_url(self, ):
        return reverse('news:slid_detail', args=[self.id])


class Messenger(models.Model):
    STATUS_CHOICES = (
        ('twitter', 'Twitter'),
        ('facebook', 'Facebook'),
        ('instagram', 'Instagram'),
    )
    url = models.CharField(max_length=250)
    types = models.CharField(max_length=15, choices=STATUS_CHOICES, null=True, blank=True)


class Messenger_chat(models.Model):
    STATUS_CHOICES = (
        ('twitter', 'Twitter'),
        ('facebook', 'Facebook'),
        ('instagram', 'Instagram'),
    )
    url = models.CharField(max_length=250)
    type = models.CharField(max_length=15, choices=STATUS_CHOICES)


class Video(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    CATEGORY_CHOICES = (
        ('eghtesadi', 'اقتصادی'),
        ('siasi', 'سیاسی'),
        ('varzeshi', 'ورزشی'),
        ('ostani', 'استانی'),
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    body = models.TextField()
    movie = models.FileField(upload_to='images/Article/')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    category = models.CharField(max_length=15, choices=CATEGORY_CHOICES)
    photo = models.ImageField(upload_to='images/Article/', null=True)

    class Meta:
        ordering = ('-publish',)

    def get_absolute_url(self, ):
        return reverse('news:video_detail', args=[self.slug, self.id])

    def __str__(self, ):
        return self.title

news/views.py
from django.shortcuts import render, get_object_or_404

from .models import Post, Slid, Messenger_chat, Video
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.views.generic import ListView


# Create your views here.


def posthome(request):
    posts = reversed(Post.objects.filter(status='published')[:8])
    slids = Slid.objects.filter(status='published')
    videos = reversed(Video.objects.filter(status='published')[:4])
    return render(request, 'post/home.html', {'posts': posts, 'slids' : slids, 'videos': videos})



# def postcategory(request):
#     posts = Post.objects.filter(status='published')
#     return render(request, 'post/categorypost.html', {'posts': posts})

class PostCategory(ListView):
    queryset = Post.objects.filter(status='published')
    context_object_name = 'posts'
    paginate_by = 2
    template_name = 'post/categorypost.html'

def videocategory(request):
    videos = Video.objects.filter(status='published')
    return render(request, 'post/categoryvideo.html', {'videos': videos})


def postsingle(request):
    posts = Post.objects.filter(status='published')
    return render(request, 'post/single.html', {'posts': posts})



def relation(request):
    return render(request, 'post/relation.html')


def contactus(request):
    return render(request, 'post/contact.html')

def postdetail(request, post, pk):
    post = get_object_or_404(Post, slug=post, id=pk)
    return render(request, 'post/single.html', {'post': post})


def videodetail(request, post, pk):
    video = get_object_or_404(Video, slug=post, id=pk)
    return render(request, 'post/video_single.html', {'video': video})


def sliddetail(request, pk):
    slidd = get_object_or_404(Slid, id=pk)
    return render(request, 'post/sliddetaill.html', {'slidd': slidd})


def messenger(request):
    twi = Messenger_chat.objects.get(type='twitter')
    fac = Messenger_chat.objects.get(type='facebook')
    ins = Messenger_chat.objects.get(type='instagram')
    urls = {'twi': twi, 'fac': fac, 'ins': ins}
    return render(request, 'post/header.html', urls)

news/templates/post/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
      <link rel="stylesheet" href={% static 'css/bootstrap.css' %}>
      <link rel="stylesheet" href={% static 'css/font-awesome.min.css' %}>
      <link rel="stylesheet" href={% static 'css/owl.carousel.css' %}>
      <link rel="stylesheet" href={% static 'css/owl.theme.default.css' %}>
      <link rel="stylesheet" href={% static 'css/style.css' %}>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <style>
            ul.menu li { display: inline-block }
            ul.menu li a { display:inline-block }
            ul.sub-menu { display: none; }
            ul.menu li:hover ul.sub-menu { display: block;background: #a2a2a2; }
            ul.sub-menu li { display: block; border-bottom: 1px solid #fff; }
            ul.sub-menu { display: none; width: 160px; position: absolute;top:42px;background: #a2a2a2;}
            ul.sub-menu li { display: block; border-bottom: 1px solid #fff; }
            ul.sub-menu li a { display: block;}
            ul.menu li:hover ul.sub-menu { display: block;background: #a2a2a2;}
            ul.menu li { display: inline-block;list-style: none;transition: all 0.4s; position: relative; }
      </style>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
{% include "post/top-bar.html" %}
{% include "post/header.html" %}
{% block content %}
{% endblock %}
{% include "post/footer.html" %}
      <script src={% static 'js/jquery.js'%}></script>
      <script src={% static 'js/bootstrap.js' %}></script>
      <script src={% static 'js/owl.carousel.min.js' %}></script>
      <script src={% static 'js/index.js' %}></script>
</body>
</html>

news/templates/post/categorypost.html
{% extends 'post/base.html' %}
{% block content %}
      <div class="latest-posts">
         <div class="container-fluid">
            <div class="blog-title-span">
               <span class="title">اخبار و مقالات</span>
            </div>
             {% for post in posts %}
            <div class="col-md-3">
               <div class="post-box">
                     <figure>
                        <img src="{{ post.photo.url }}" alt="">
                        <figcaption class="meta-fig">
                           <span><i class="fa fa-clock-o"></i>{{ post.publish }}</span>&nbsp;
                        </figcaption>
                        <figcaption class="view">
                           <span>{{ post.category }}</span>
                        </figcaption>
                     </figure>
                     <div class="text-p">
                        <h5>{{ post.title }}</h5>
                        <p>{{ post.body }}</p>
                        <div class="text-rigt">
                  <a href="{{ post.get_absolute_url }}">ادامه ...</a></div>
                  </div>
               </div>
            </div>
             {% endfor %}
            <div class="col-md-12 text-center">
               <nav aria-label="Page navigation example">
                  <ul class="pagination">
                     {% if page_obj.has_previous %}
                     <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">قبلی</a></li>
                     {% endif %}


                  {% for i in page_obj.pagintor.page_range %}
                      {% if i == page_obj.number %}
                     <li class="page-item"><a class="page-link" href="#">{{ i }}</a></li>
                      {% else %}
                        {{ i }}
                      {% endif %}
                  {% endfor %}

                  
                     {% if page_obj.has_next %}
                     <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">بعدی</a></li>
                     {% endif %}
                  </ul>
               </nav>
            </div>
         </div>
      </div>
      <div class="bg"></div>
{% endblock %}

news/templates/post/categoryvideo.html
{% extends 'post/base.html' %}
{% block content %}
      <div class="latest-posts">
         <div class="container-fluid">
            <div class="blog-title-span">
               <span class="title">اخبار و مقالات</span>
            </div>
             {% for video in videos %}
            <div class="col-md-3">
               <div class="post-box">
                     <figure>
                        <img src="{{ video.photo.url }}" alt="">
                        <figcaption class="meta-fig">
                           <span><i class="fa fa-clock-o"></i>{{ video.publish }}</span>&nbsp;
                        </figcaption>
                        <figcaption class="view">
                           <span>{{ video.category }}</span>
                        </figcaption>
                     </figure>
                     <div class="text-p">
                        <h5>{{ video.title }}</h5>
                        <p>{{ video.body }}</p>
                        <div class="text-rigt">
                  <a href="{{ video.get_absolute_url }}">ادامه ...</a></div>
                  </div>
               </div>
            </div>
             {% endfor %}
            <div class="col-md-12 text-center">
               <nav aria-label="Page navigation example">
                  <ul class="pagination">
                     <li class="page-item"><a class="page-link" href="#">قبلی</a></li>
                     <li class="page-item"><a class="page-link" href="#">1</a></li>
                     <li class="page-item"><a class="page-link" href="#">2</a></li>
                     <li class="page-item"><a class="page-link" href="#">3</a></li>
                     <li class="page-item"><a class="page-link" href="#">بعدی</a></li>
                  </ul>
               </nav>
            </div>
         </div>
      </div>
      <div class="bg"></div>
{% endblock %}

news/templates/post/contact.html
{% extends "post/base.html" %}
{% load static %}
{% block content %}
      {# relation #}{# relation #}{# relation #}{# relation #}{# relation #}{# relation #}{# relation #}{# relation #}
      <div class="single_post">
         <div class="container-fluid">
            <div class="col-md-2"></div>
            <div class="col-md-8">
               <div class="post_content text-center">
                  <p>تماس با ما</p>
               </div>
            </div>
         </div>
      </div>
      {# relation #}{# relation #}{# relation #}{# relation #}{# relation #}{# relation #}{# relation #}{# relation #}
      <div class="clear-fix"></div>
      <div class="bg"></div>
{% endblock %}

news/templates/post/footer.html
 <div class="footer">
        <div class="container-fluid">
           <div class="col-md-5">
              <div class="footer-box">
                 <span class="title">مجله mrnews</span>
                 <p>متن ساختگی با تولید سادگی نامفهوم تولید سادگی از صنعت متن ساختگی با تولید سادگی نامفهوم تولید
                    سادگی از صنعت متن ساختگی با تولید سادگی نامفهوم تولید سادگی از صنعت متن ساختگی با تولید سادگی از
                    صنعت متن ساختگی با تولید سادگی نامفهوم تولید سادگی از صنعت متن ساختگی با تولید سادگی نامفهوم
                    تولید سادگی از صنعت متن ساختگی بام تولید سادگی از صنعت متن ساختگی با تولید سادگی نامفهوم تولید
                    سادگی از صنعت متن ساختگی با تولید سادگی نامفهوم تولید سادگی از صنعت متن سادگی نامفهوم تولید
                    سادگی از صنعت
                 </p>
              </div>
           </div>
           <div class="col-md-2">
              <div class="footer-box">
                 <span class="title">دسترسی سریع</span>
                 <ul>
                    <li><a href="#">موضوعی</a></li>
                    <li><a href="#">قوانین</a></li>
                    <li><a href="#">نشریات</a></li>
                    <li><a href="#">موضوعی</a></li>
                    <li><a href="#">خبرنامه</a></li>
                 </ul>
              </div>
           </div>

           <div class="col-md-3">
              <div class="footer-box contact-box">
                 <span class="title">تماس با ما</span>
                 <p><i class="fa fa-phone"></i> 09028468446</p>
                 <p><i class="fa fa-phone"></i> 09336636892</p>
                 <p><i class="fa fa-envelope-o"></i> info@seo90.ir</p>
                 <p><i class="fa fa-map-marker"></i> تبریز </p>
              </div>
           </div>
           <div class="clear-fix"></div>
        </div>
     </div>
     <div class="end-wrapper">
        <div class="container-fluid">
           <div class="col-md-6">
              <div class="copy-r">
                 <p>&copy; تمامی حقوق متعلق به mrnews می باشد</p>
              </div>
           </div>
           <div class="col-md-6">
              <div class="creator text-left">
              </div>
           </div>
        </div>
     </div>
     <div class="bg"></div>

news/templates/post/header.html
 <div class="main-header">
         <div class="container-fluid">
            <div class="col-md-10">
               <div class="main-menu">
                  <ul class="menu">
                     <li><a href='/'>خانه</a></li>
                     <li>
                        <a href="{% url 'news:post_category' %}">اخبار <i class="fa fa-caret-down"></i></a>
                        <ul class="sub-menu" style="background: white; z-index: 100" >
                           <li class="menu-item"><a href="#">اقتصادی</a></li>
                           <li class="menu-item"><a href="#">سیاسی</a></li>
                           <li class="menu-item"><a href="#">ورزشی</a></li>
                           <li class="menu-item"><a href="#">استانی</a></li>
                        </ul>
                     </li>
                      <li>
                        <a href="{% url 'news:video_category' %}">ویدئو ها <i class="fa fa-caret-down"></i></a>
                        <ul class="sub-menu" style="background: white; z-index: 100" >
                           <li class="menu-item"><a href="#">اقتصادی</a></li>
                           <li class="menu-item"><a href="#">سیاسی</a></li>
                           <li class="menu-item"><a href="#">ورزشی</a></li>
                           <li class="menu-item"><a href="#">استانی</a></li>
                        </ul>
                     </li>
                  </ul>
               </div>
            </div>
            <div class="col-md-2">
               <div class="social-box">
                  <ul>
                     <li><a href="https://twitter.com" target="_blank"><i class="fa fa-twitter"></i></a></li>
                     <li><a href="https://facebook.com" target="_blank"><i class="fa fa-facebook"></i></a></li>
                     <li><a href="https://instagram.com" target="_blank"><i class="fa fa-instagram"></i></a></li>
                  </ul>
               </div>
            </div>
         </div>
      </div>

news/templates/post/relation.html
{% extends "post/base.html" %}
{% load static %}
{% block content %}
      {# relation #}{# relation #}{# relation #}{# relation #}{# relation #}{# relation #}{# relation #}{# relation #}
      <div class="single_post">
         <div class="container-fluid">
            <div class="col-md-2"></div>
            <div class="col-md-8">
               <div class="post_content text-center">
                  <p>ارتباط با ما</p>
               </div>
            </div>
         </div>
      </div>
      {# relation #}{# relation #}{# relation #}{# relation #}{# relation #}{# relation #}{# relation #}{# relation #}
      <div class="clear-fix"></div>
      <div class="bg"></div>
{% endblock %}

news/templates/post/single.html
{% extends "post/base.html" %}
{% load static %}
{% block content %}
      <div class="single_post">
         <div class="container-fluid">
            <div class="col-md-2"></div>
            <div class="col-md-8">
               <div class="row">
                  <div class="col-md-2"></div>
                  <div class="col-md-8">
                     <div class="post_img">
                        <img src="{% static 'img/tabligh.png' %}" alt="">
                     </div>
                  </div>
                  <div class="col-md-2"></div>
               </div>
               <div class="posts_meta text-center">
                  <span><i class="fa fa-archive"></i> {{ post.category }}</span>
                  <span><i class="fa fa-calendar"></i>{{ post.publish }}</span>
               </div>
               <div class="post_content">
                  <h4>{{ post.title }}</h4>
                  <img src="{{ post.photo.url }}" alt="" height="300px">
                  <p>{{ post.body|linebreaks }}</p>
               </div>
               <div class="comments_form">
                  <h5>دیدگاه شما </h5>
                  <form>
                     <div class="form-row">
                        <div class="col-md-6">
                           <input type="text" class="form-control" placeholder="نام شما">
                        </div>
                        <div class="col-md-6">
                           <input type="email" class="form-control" placeholder="ایمیل">
                        </div>
                        <div class="col-md-12">
                           <textarea class="form-control" placeholder="نظر شما ..."></textarea>
                        </div>
                        <div class="col-md-12">
                           <div class="text-left">
                              <button class="btn btn-primary">ثبت نظر</button>
                           </div>
                        </div>
                     </div>
                  </form>
               </div>
            </div>
         </div>
      </div>
      <div class="clear-fix"></div>
      <div class="bg"></div>
{% endblock %}

news/templates/post/sliddetaill.html
{% extends "post/base.html" %}
{% load static %}
{% block content %}
      <div class="single_post">
         <div class="container-fluid">
            <div class="col-md-2"></div>
            <div class="col-md-8">
               <div class="row">
                  <div class="col-md-2"></div>
                  <div class="col-md-8">
                     <div class="post_img">
                        <img src="{% static 'img/tabligh.png' %}" alt="">
                     </div>
                  </div>
                  <div class="col-md-2"></div>
               </div>
               <div class="posts_meta text-center">
                  <span><i class="fa fa-archive"></i> {{ slidd.category }}</span>
                  <span><i class="fa fa-calendar"></i>{{ slidd.publish }}</span>
               </div>
               <div class="post_content">
                  <h4>{{ slidd.title }}</h4>
                   <img src="{{ slidd.photo.url }}" alt="" height="200px" width="400px">
                  <p>{{ slidd.body }}</p>
               </div>
               <div class="comments_form">
                  <h5>دیدگاه شما </h5>
                  <form>
                     <div class="form-row">
                        <div class="col-md-6">
                           <input type="text" class="form-control" placeholder="نام شما">
                        </div>
                        <div class="col-md-6">
                           <input type="email" class="form-control" placeholder="ایمیل">
                        </div>
                        <div class="col-md-12">
                           <textarea class="form-control" placeholder="نظر شما ..."></textarea>
                        </div>
                        <div class="col-md-12">
                           <div class="text-left">
                              <button class="btn btn-primary">ثبت نظر</button>
                           </div>
                        </div>
                     </div>
                  </form>
               </div>
            </div>
         </div>
      </div>
      <div class="clear-fix"></div>
      <div class="bg"></div>
{% endblock %}

news/templates/post/top-bar.html
<div class="top-bar">
        <div class="container-fluid">
           <div class="col-md-6">
              <div class="search-btn">
                 <span><i class="fa fa-search"></i></span>
              </div>
           </div>
           <div class="col-md-6">
              <div class="top-cat-box">
                 <div class="col-md-12">
                    <div class="menu">
                       <ul>
                          <li><a href="{% url 'news:contact_us' %}">تماس با ما</a></li>
                          <li><a href="{% url 'news:post_ralation' %}">درباره ما</a></li>
                       </ul>
                    </div>
                 </div>
                 <!-- <div class="col-md-3">
                    <div class="show-cat">
                        <span>
                            دسته ها
                            <i class="fa fa-bars"></i>
                        </span>
                    </div>
                    </div> -->
              </div>
           </div>
        </div>
     </div>

news/templates/post/video_single.html
{% extends "post/base.html" %}
{% load static %}
{% block content %}
      <div class="single_post">
         <div class="container-fluid">
            <div class="col-md-2"></div>
            <div class="col-md-8">
               <div class="row">
                  <div class="col-md-2"></div>
                  <div class="col-md-8">
                     <div class="post_img">
                        <img src="{% static 'img/tabligh.png' %}" alt="">
                     </div>
                  </div>
                  <div class="col-md-2"></div>
               </div>
               <div class="posts_meta text-center">
                  <span><i class="fa fa-archive"></i> {{ post.category }}</span>
                  <span><i class="fa fa-calendar"></i>{{ post.publish }}</span>
               </div>
               <div class="post_content">
                  <h2 style="color: orange">{{ video.title }}</h2>
                   <div style="text-align: center">
                      <video src="{{ video.movie.url }}" controls alt="" height="300px" style="text-align: center; margin: auto; border-radius: 15px" >
                   </div>
                  <p>{{ video.body|linebreaks }}</p>
               </div>
               <div class="comments_form">
                  <h5>دیدگاه شما </h5>
                  <form>
                     <div class="form-row">
                        <div class="col-md-6">
                           <input type="text" class="form-control" placeholder="نام شما">
                        </div>
                        <div class="col-md-6">
                           <input type="email" class="form-control" placeholder="ایمیل">
                        </div>
                        <div class="col-md-12">
                           <textarea class="form-control" placeholder="نظر شما ..."></textarea>
                        </div>
                        <div class="col-md-12">
                           <div class="text-left">
                              <button class="btn btn-primary">ثبت نظر</button>
                           </div>
                        </div>
                     </div>
                  </form>
               </div>
            </div>
         </div>
      </div>
      <div class="clear-fix"></div>
      <div class="bg"></div>
{% endblock %}